# -*- coding: utf-8 -*-
"""rifanas_ai_a_24 - model_covid_template.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XaWhocH3AQjWsLYAp7zp6STdA-Y77V8b
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import cv2

from tensorflow.keras.models import Sequential
from tensorflow import keras
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout , Input
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix

import tensorflow as tf

SEED = 42

np.random.seed(SEED)
tf.random.set_seed(SEED)

from google.colab import drive
drive.mount('/content/drive')

images = np.load('/content/CovidImages.npy')

labels = pd.read_csv('/content/CovidLabels.csv')

print(images.shape)

plt.imshow(images[5])
plt.title(labels.iloc[5, 0])
plt.axis('off')
plt.show()

plt.figure(figsize=(12, 9))
for i in range(12):
  plt.subplot(3, 4, i+1)
  plt.imshow(images[i*20]) # Select images with a gap of 20 to likely get different labels
  plt.title(labels.iloc[i*20, 0])
  plt.axis('off')
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 6))
sns.countplot(x='Label', data=labels, palette='viridis')
plt.title('Proportion of Each Label in the Dataset')
plt.xlabel('Label')
plt.ylabel('Count')
plt.show()

labels['Label'] = labels['Label'].map({'Covid': 1, 'Normal': 0})

X_train, X_temp, y_train, y_temp = train_test_split(images, labels['Label'], test_size=0.3, random_state=42, stratify=labels['Label'])


X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

print(f"Training set shape: {X_train.shape}, {y_train.shape}")
print(f"Validation set shape: {X_val.shape}, {y_val.shape}")
print(f"Test set shape: {X_test.shape}, {y_test.shape}")

X_train_normalized = X_train / 255.0
X_val_normalized = X_val / 255.0
X_test_normalized = X_test / 255.0

print(f"Normalized training set min/max: {X_train_normalized.min()}/{X_train_normalized.max()}")
print(f"Normalized validation set min/max: {X_val_normalized.min()}/{X_val_normalized.max()}")
print(f"Normalized test set min/max: {X_test_normalized.min()}/{X_test_normalized.max()}")

import gc
tf.keras.backend.clear_session()
gc.collect()

model_cnn1 = Sequential([
    Input(shape=(128, 128, 3)),

    # First conv+pooling layer
    Conv2D(32, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),

    # Second conv+pooling layer
    Conv2D(64, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),

    # Combination 3: Conv + Pooling layer
    Conv2D(128, (3, 3), activation='relu', padding='same'),
    MaxPooling2D((2, 2)),

    Flatten(),
    Dense(128, activation='relu'),


    Dense(1, activation='sigmoid')
])

optimizer = tf.keras.optimizers.Adam()
model_cnn1.compile(optimizer=optimizer,
              loss='binary_crossentropy',
              metrics=['accuracy'])
model_cnn1.summary()

import time

start_time = time.time()

# Fit the model
history = model_cnn1.fit(X_train_normalized, y_train,
                        epochs=10,
                        batch_size=8)

end_time = time.time()
training_time = end_time - start_time

print(f"Training completed in {training_time:.2f} seconds.")


train_loss, train_acc = model_cnn1.evaluate(X_train_normalized, y_train, verbose=0)


val_loss, val_acc = model_cnn1.evaluate(X_val_normalized, y_val, verbose=0)


y_train_pred_prob = model_cnn1.predict(X_train_normalized)
y_val_pred_prob = model_cnn1.predict(X_val_normalized)

# (assuming threshold of 0.5)
y_train_pred = (y_train_pred_prob > 0.5).astype(int)
y_val_pred = (y_val_pred_prob > 0.5).astype(int)

# Get classification reports
train_report = classification_report(y_train, y_train_pred, output_dict=True)
val_report = classification_report(y_val, y_val_pred, output_dict=True)

train_recall_covid = train_report['1']['recall']
val_recall_covid = val_report['1']['recall']

new_row = pd.DataFrame([{
    'Model Name': 'CNN Model (3 Conv Layers)',
    'Train Accuracy': train_acc,
    'Validation Accuracy': val_acc,
    'Train Recall (COVID)': train_recall_covid,
    'Validation Recall (COVID)': val_recall_covid
}])
evaluation_result = pd.concat([evaluation_result, new_row], ignore_index=True)

# Display
print("Evaluation Results:")
evaluation_result

"""Observation:

• Validation accuracy was 97.37% and COVID recall was 100%

"""